version: "3.8"

services:
  cli:
    container_name: cdt
    build: ./services/app
    command: /bin/bash
    volumes:
      - ./services/app/:/home/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:14-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cdt
      - POSTGRES_PASSWORD=cdt
      - POSTGRES_DB=compound_data_tools

volumes:
  postgres_data:
